/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:472fb856-e263-47af-b3da-07d9d2bfb156",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_l3VdV2qLE",
    "aws_user_pools_web_client_id": "2bk6nfd0vmm53dvpjqurj10gio",
    "oauth": {}
};


export default awsmobile;
